### ISSUE TITLE
light turns on suddenly when set to turn on over 30 minutes

### ISSUE THREAD

**Issue by zenodotus280** [AdnanValdes/ycs#2]
I am running YCS in Docker. My ENV variables are set to turn the light off over 2 hours at sunset and turn on at sunrise over 30 minutes. The light will suddenly turn on in the morning as if it's never seen an ENV variable in its life. It does not respect the variable and certainly isn't validated by it. The sunset dimming works flawlessly.

**Comment by AdnanValdes** [comment]
Could include the logs for this, as well as the ON_TRANSITION, ON_START_TIME,SUN_UPDATE_TIME, and PING_BULB_FREQ variables you used?

**Comment by AdnanValdes** [comment]
The issue should now be fixed. The "auto_on" parameter for the Bulb was left on, as I use it for development purposes. The latest commit fixes that. In docker, pull `einhard/ycs:latest` and see if it works, please.

I'll leave this issue open for now and will wait to hear back from you.

**Comment by zenodotus280** [comment]
Works as expected. Thanks!
